package Amazon.Enums;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    BROWSER;

}
